@startuml
class User {
	**id : int**
	email : string
	roles : array
	password : string
	<color:#0000dd>client : Clients</color>
	user_name : string
}

class Vendeurs {
	**id : int**
	id_vendeur : int
	nom_vend : string
	email_vend : string
	phone_vend : int
	<color:#0000dd>client : Clients</color>
}

class Produits {
	**id : int**
	nom_produit : string
	desc_produit : string
	achat_prix : string
	vent_prix : string
	photo : string
	<color:#0000dd>categorie : Categories</color>
}

class LivraisonNote {
	**id : int**
	<color:#0000dd>commande : Commandes</color>
	statutLivraison : string
	dateLivraison : DateTime
	noteLivraison : string
}

class Clients {
	**id : int**
	typeClient : string
	conditionPaiement : string
	adresseFacturation : string
	adresseLivraison : string
	codePostalFacturation : string
	codePostalLivraison : string
	<color:#0000dd>user : User</color>
	<color:#0000dd>vendeurs : Vendeurs[]</color>
	<color:#0000dd>commandes : Commandes[]</color>
	client_email : string
	client_phone : string
}

class Factures {
	**id : int**
	<color:#0000dd>commande : Commandes</color>
	dateFacture : DateTime
	montantTotal : string
	statutPaiement : string
}

class Fournisseurs {
	**id : int**
	id_fournisseur : int
	nom_fournisseur : string
	email_fou : string
	phone_fou : int
	produit_exclusif : string
}

class Categories {
	**id : int**
	nom_cat : string
	desc_cat : string
	<color:#0000dd>produits : Produits[]</color>
}

class Commandes {
	**id : int**
	<color:#0000dd>client : Clients</color>
	<color:#0000dd>produits : Produits[]</color>
	quantite : int
	prixUnitaire : string
	prixTotal : string
	<color:#0000dd>livraisonNote : LivraisonNote</color>
	<color:#0000dd>facture : Factures</color>
}

User "1"--"1" Clients
Vendeurs "*"--"1" Clients
Produits "*"--"1" Categories
LivraisonNote "1"--"1" Commandes
Clients "1"--"*" Vendeurs
Clients "1"--"*" Commandes
Factures "1"--"1" Commandes
Commandes "*"--"*" Produits


hide methods

hide circle

@enduml
