@startuml
class User {
	**id : int**
	email : string
	roles : array
	password : string
	<color:#0000dd>client : Clients</color>
	user_name : string
}

class Vendeurs {
	**id : int**
	id_vendeur : int
	nom_vend : string
	email_vend : string
	phone_vend : int
	<color:#0000dd>client : Clients</color>
}

class Produits {
	**id : int**
	nom_produit : string
	desc_produit : string
	achat_prix : string
	vent_prix : string
	photo : string
	<color:#0000dd>categorie : Categories</color>
}

class LivraisonNote {
	**id : int**
	id_liv_note : int
	<color:#0000dd>id_commande : Commandes</color>
	statut_liv : string
	date_liv : DateTime
	note_liv : string
}

class Clients {
	**id : int**
	type_client : string
	condition_paiment : string
	address_facturation : string
	address_livrasion : string
	<color:#0000dd>user : User</color>
	<color:#0000dd>id_vend : Vendeurs[]</color>
	<color:#0000dd>commandes : Commandes[]</color>
	client_cp : string
	livrasion_cp : string
}

class Factures {
	**id : int**
	id_facture : int
	<color:#0000dd>id_commande : Commandes</color>
	date_facture : DateTime
	montant_total : string
	paiment_statut : string
}

class Fournisseurs {
	**id : int**
	id_fournisseur : int
	nom_fournisseur : string
	email_fou : string
	phone_fou : int
	produit_exclusif : string
}

class Categories {
	**id : int**
	nom_cat : string
	desc_cat : string
	<color:#0000dd>produits : Produits[]</color>
}

class Commandes {
	**id : int**
	id_commande : int
	<color:#0000dd>client : Clients</color>
	<color:#0000dd>id_produit : Produits[]</color>
	quantité : int
	unit_prix : string
	total_prix : string
}

User "1"--"1" Clients
Vendeurs "*"--"1" Clients
Produits "*"--"1" Categories
LivraisonNote "1"--"1" Commandes
Clients "1"--"*" Vendeurs
Clients "1"--"*" Commandes
Factures "1"--"1" Commandes
Commandes "*"--"1" Clients
Commandes "*"--"*" Produits


hide methods

hide circle

@enduml
